name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Setup iOS build environment
      run: |
        # Install CocoaPods
        sudo gem install cocoapods
        
        # Run iOS build fix script
        chmod +x ios_build_fix.sh
        ./ios_build_fix.sh
        
    - name: Verify iOS configuration
      run: |
        # Copy provisioning profile to iOS directory if it exists
        if [ -f "punchio.mobileprovision" ]; then
          cp punchio.mobileprovision ios/
          echo "Provisioning profile copied to iOS directory"
        fi
        
        # Verify Xcode project configuration
        echo "Checking Xcode project configuration..."
        grep -n "CODE_SIGN_STYLE" ios/Runner.xcodeproj/project.pbxproj || echo "CODE_SIGN_STYLE not found"
        grep -n "DEVELOPMENT_TEAM" ios/Runner.xcodeproj/project.pbxproj || echo "DEVELOPMENT_TEAM not found"
        grep -n "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj || echo "PRODUCT_BUNDLE_IDENTIFIER not found"
        
    - name: Build iOS app
      run: |
        # Set environment variables for build
        export FLUTTER_BUILD_MODE=release
        
        # Build iOS app with automatic code signing
        flutter build ipa \
          --release \
          --export-options-plist=ios/ExportOptions.plist \
          --verbose
          
    - name: Alternative build with xcodebuild (if Flutter build fails)
      if: failure()
      run: |
        echo "Flutter build failed, trying direct xcodebuild..."
        cd ios
        
        # Clean build directory
        rm -rf build/
        
        # Build with xcodebuild with automatic code signing
        xcodebuild -workspace Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -destination generic/platform=iOS \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=MNRC5F55U3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.punchio.punchi \
          archive \
          -archivePath Runner.xcarchive \
          -verbose
          
        # Export IPA from archive
        xcodebuild -exportArchive \
          -archivePath Runner.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist ExportOptions.plist \
          -allowProvisioningUpdates \
          -verbose
          
        cd ..
        
    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-artifacts
        path: |
          build/ios/ipa/*.ipa
          ios/build/*.ipa
        retention-days: 7
        
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ios-build-logs
        path: |
          build/
          ios/build/
        retention-days: 3